name: Terraform CI

#Permissions:

permissions:
    id-token: write
    contents: read
on:
  pull_request:
  push:
    branches:
      - main

# ---------- DEV ----------
jobs:
  terraform-dev:
    name: Terraform checks (dev & prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::724134393251:role/github-actions-terraform-dev
            aws-region: us-east-1

      - name: Terraform init (dev)
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Terraform fmt (dev)
        working-directory: environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform validate (dev)
        working-directory: environments/dev
        run: terraform validate 

      - name: Terraform plan (dev)
        working-directory: environments/dev
        run: terraform plan -input=false

      # ---------- PROD ----------
  terraform-prod:
    name: Terraform checks (prod)
    runs-on: ubuntu-latest
    needs: terraform-dev
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (prod)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::724134393251:role/github-actions-terraform-prod
            aws-region: us-east-1
            
      - name: Terraform fmt (prod)
        working-directory: environments/prod
        run: terraform fmt -check -recursive

      - name: Terraform init (prod)
        working-directory: environments/prod
        run: terraform init -backend=false

      - name: Terraform validate (prod)
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform plan (prod)
        working-directory: environments/prod
        run: terraform plan -input=false
