name: Terraform CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform checks (dev & prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # ---------- DEV ----------
      - name: Terraform fmt (dev)
        working-directory: environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform init (dev)
        working-directory: environments/dev
        run: terraform init -backend=false

      - name: Terraform validate (dev)
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform plan (dev)
        working-directory: environments/dev
        run: terraform plan -input=false

      # ---------- PROD ----------
      - name: Terraform fmt (prod)
        working-directory: environments/prod
        run: terraform fmt -check -recursive

      - name: Terraform init (prod)
        working-directory: environments/prod
        run: terraform init -backend=false

      - name: Terraform validate (prod)
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform plan (prod)
        working-directory: environments/prod
        run: terraform plan -input=false
